import styles from './layout.module.css';
import Head from "next/head";
import Link from 'next/link'

export default function Layout({children,title}){
    return(
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name={title} content="Generated by Kong" />
            </Head>
            <header className={styles.header}>
                <h1 className={styles.h}>Header</h1>
            </header>
            <main className={styles.main}>{children}</main>
            <footer className={styles.footer}>Footer</footer>
        </div>
    )
}